### ISSUE TITLE
Requested entity was not found

### ISSUE THREAD

**Issue by wojcikcp** [nikaia/translation-sheet#10]
```
TS_SPREADSHEET_ID=xx
```

It should be some random number or what?

```
[Google_Service_Exception]                             
  {                                                      
    "error": {                                           
      "code": 404,                                       
      "message": "Requested entity was not found.",      
      "errors": [                                        
        {                                                
          "message": "Requested entity was not found.",  
          "domain": "global",                            
          "reason": "notFound"                           
        }                                                
      ],                                                 
      "status": "NOT_FOUND"                              
    }                                                    
  }    
```

**Comment by vinsonyung** [comment]
@wojcikcp 
/*
    |--------------------------------------------------------------------------
    | Spreadsheet
    |--------------------------------------------------------------------------
    | The spreadsheet that will be used for translations.
    | You need to create a new empty spreadsheet manually and fill its ID here.
    | You can find the ID in the spreadsheet URL.
    | (https://docs.google.com/spreadsheets/d/{spreadsheetId}/edit#gid=0)
    */
    'spreadsheetId' => env('TS_SPREADSHEET_ID', '***'),
