### ISSUE TITLE
[Bug] Cannot publish config file

### ISSUE THREAD

**Issue by vinsonyung** [nikaia/translation-sheet#11]
**Development environment:**
Ubuntu 16.04 LTS
Laravel Homestead 2.1.0
Laravel 5.4.x

After running this command in console, no file is copied to config folder
`php artisan vendor:publish --provider="Nikaia\TranslationSheet\ServiceProvider"`

**Comment by Iseldore** [comment]
You have to do this : 
`php artisan vendor:publish --provider="Nikaia\TranslationSheet\TranslationSheetServiceProvider"`
