### ISSUE TITLE
[Bug] Unable to install via composer due to google/apiclient v2.1.2 being installed

### ISSUE THREAD

**Issue by adrianmejias** [nikaia/translation-sheet#14]
Unable to call `composer require nikaia/translation-sheet` in terminal due to **google/apiclient v2.1.2** being installed:

![screen shot 2017-05-31 at 4 20 13 pm](https://cloud.githubusercontent.com/assets/1440288/26654613/1641a868-461d-11e7-93b7-cb9d805a20e4.png)

**google/apiclient ^2.1** in _composer.json_ (being used by another package):

![screen shot 2017-05-31 at 4 21 54 pm](https://cloud.githubusercontent.com/assets/1440288/26654666/4d7e61a4-461d-11e7-8d7c-ba36fbcba521.png)

**Comment by nbourguig** [comment]
Hi,

Are you using another version of google/client elsewhere, or maybe another package ?

**Comment by adrianmejias** [comment]
Looks like I have **google/apiclient v2.1.3** installed. Which means another plugin is installing **v2.1.3**... I'll have to sift through and find out which one.

![screen shot 2017-06-23 at 9 44 04 am](https://user-images.githubusercontent.com/1440288/27487181-9753a158-57f8-11e7-8b22-bec6704d5edc.png)

**Comment by nbourguig** [comment]
It seems there were some breaking changes that introduces some issues. That's why i explicitly set the version in https://github.com/nikaia/translation-sheet/releases/tag/1.1.0

I will look into it as soon as I have some time.

**Comment by nbourguig** [comment]
Hi,

Let me if this solves your issue.
https://github.com/nikaia/translation-sheet/releases/tag/1.2.0
