### ISSUE TITLE
 Undefined index: properties

### ISSUE THREAD

**Issue by jasperjorna** [nikaia/translation-sheet#16]
Hi,

Thanks for this clever package!

I'm running into a problem after I've setup a fresh spreadsheet, here's what happens:

```
php artisan translation_sheet:setup
Setting up Translations sheet
Adding Meta sheet
Done. Spreasheet is ready.
```

```
php artisan translation_sheet:prepare
Scanning local languages files
Rewriting:
/home/vagrant/code/sites/nebimusedtrucks.dev/resources/lang/lots_of_files_here
/home/vagrant/code/sites/nebimusedtrucks.dev/resources/lang/lots_of_files_here
...
```

```
php artisan translation_sheet:push
Scanning languages files
Preparing spreasheet for new write operation

[ErrorException]
Undefined index: properties
```

Edit: seems like this bug was introduced in `1.2.*`, as `1.1.1` still works.

Thanks!

**Comment by nbourguig** [comment]
Hi,

Thx.

Right, there was an error with google/apiclient >= 2.2. (I'm might be relying on some internal stuff on their sdk. I may need to get a closer look to see if I can rely only on public stuff.)

You can go ahead and test with 1.2.2 release.


Feel free to reopen if it does not solve your issue.
