### ISSUE TITLE
Document travis encrypted env variable

### ISSUE THREAD

**Issue by Elhebert** [nikaia/translation-sheet#19]
I did a fork of your project (and submitted #18), but when I tried to run travis on my fork, it failed due to the absence of the encrypted env variable you are using in the `.travis.yml` file.

It might be a good idea to document what is needed for us to run the tests on our own.

**Comment by nbourguig** [comment]
Hi,

I updated the Readme file to include a section on travis. Let me know if it did the trick.

https://github.com/nikaia/translation-sheet/#travis
