### ISSUE TITLE
Support php 7.2

### ISSUE THREAD

**Issue by Thomasvanwijnen** [nikaia/translation-sheet#23]
On php 7.2 I encountered the error: "count(): Parameter must be an array or an object that implements Countable" when using the 'php artisan translation_sheet:push' command

Spreadsheet.php line: 53 in the getTranslationsCount() method. 

Fix: 

```
public function getTranslationsCount()
{
    if(is_array($this->translations)){
        return count($this->translations);
    }

    return strlen($this->translations);
}
```

**Comment by balping** [comment]
https://github.com/nikaia/translation-sheet/pull/22

**Comment by nbourguig** [comment]
Fixed.
