### ISSUE TITLE
Support for nested lang files

### ISSUE THREAD

**Issue by tmihetec** [nikaia/translation-sheet#24]
Am i missing something, or there's no suport for nested lang files? ie:

lang
    - en
    - - - set1
    - - - - - trans1.php
   
which should be accessed like @lang(set1/trans1.key)

btw, i really like idea behind this package :)

**Comment by nbourguig** [comment]
I'm afraid not. 
If this is a thing, i'll be happy to check a pull request.

**Comment by pmochine** [comment]
I just wanted to open an issue, I need this as well!
