### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by apair** [nikaia/translation-sheet#28]
After success setup and prepare with artisan command, when I want to push it, get this error after **Updating header**

```
ErrorException  : count(): Parameter must be an array or an object that implements Countable

  at */vendor/nikaia/translation-sheet/src/Spreadsheet.php:53
    49|     }
    50| 
    51|     public function getTranslationsCount()
    52|     {
  > 53|         return count($this->translations);
    54|     }
    55| 
    56|     public function getId()
    57|     {

  Exception trace:

  1   count()
      /*/vendor/nikaia/translation-sheet/src/Spreadsheet.php:53

  2   Nikaia\TranslationSheet\Spreadsheet::getTranslationsCount()
      /*/vendor/nikaia/translation-sheet/src/Spreadsheet.php:130
```

**Comment by litlife** [comment]
I have the same error when use command php artisan translation_sheet:push
`
Scanning languages files
Preparing spreasheet for new write operation
Updating header

In Spreadsheet.php line 53:
                                                                              
  [ErrorException]                                                            
  count(): Parameter must be an array or an object that implements Countable  
                                                                              

Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 count() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Spreadsheet.php:53
 Nikaia\TranslationSheet\Spreadsheet->getTranslationsCount() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Spreadsheet.php:130
 Nikaia\TranslationSheet\Spreadsheet->translationsSheetCoordinates() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Sheet/TranslationsSheet.php:24
 Nikaia\TranslationSheet\Sheet\TranslationsSheet->emptyCoordinates() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Sheet/TranslationsSheet.php:160
 Nikaia\TranslationSheet\Sheet\TranslationsSheet->updateHeaderRow() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Pusher.php:41
 Nikaia\TranslationSheet\Pusher->push() at /home/vagrant/project/vendor/nikaia/translation-sheet/src/Commands/Push.php:16
 Nikaia\TranslationSheet\Commands\Push->handle() at n/a:n/a
 call_user_func_array() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
 Illuminate\Container\Container->call() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:184
 Illuminate\Console\Command->execute() at /home/vagrant/project/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:171
 Illuminate\Console\Command->run() at /home/vagrant/project/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /home/vagrant/project/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /home/vagrant/project/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Console/Application.php:89
 Illuminate\Console\Application->run() at /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /home/vagrant/project/artisan:35
`

**Comment by nbourguig** [comment]
This is maybe related to #21 

Please update to a recent version. 

Feel free to reopen this issue if it not resolved.
