### ISSUE TITLE
Option to exclude vendor translation

### ISSUE THREAD

**Issue by Andicot** [nikaia/translation-sheet#29]
It would be useful to have an option to exclude the vendor folder translation

**Comment by nbourguig** [comment]
Sure. A pull request is welcome.

**Comment by DaniTulp** [comment]
Is there any update on this, I would also love to be able to exclude validation translations. I could also work on this if @kslr can't do it!

**Comment by kslr** [comment]
You can take over this thing

**Comment by nbourguig** [comment]
You can now exclude translation keys patterns. 
https://github.com/nikaia/translation-sheet/#excluding-translations
