### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by KevinPeters89** [nikaia/translation-sheet#3]
Hi,

I have followed your setup to the letter, but I get the following result when I try to do the artisan commands.

$ php artisan translation_sheet:prepare

                              
  [InvalidArgumentException]  
  file does not exist

**Comment by KevinPeters89** [comment]
Nevermind, silly type-o :D

**Comment by nbourguig** [comment]
A better error message is needed I guess. Thx for reporting.
