### ISSUE TITLE
Option to export each language to different file or tab

### ISSUE THREAD

**Issue by AidasK** [nikaia/translation-sheet#33]
It would be useful to export each language to different file or tab. Because current behaviour is useless when exporting 10 or more languages. 
This is also needed, because I want to share each file with different translator.

**Comment by billriess** [comment]
I don't think this would be a good idea. Splitting the translations into different tabs or files would allow for more mistakes/conflicts. You could always split it out yourself, hand it off to a translator and then import it back into the same file if you really needed that.

**Comment by nbourguig** [comment]
The package was build around the idea of one sheet. I can see that splitting the locales overmultiple sheets can be useful in some situations. But I cannot see how it can be implemented easily without breaking the previous versions.
