### ISSUE TITLE
Ability to work with .json translation files

### ISSUE THREAD

**Issue by satoved** [nikaia/translation-sheet#34]
Json format is not currently supported?

https://laravel-news.com/json-based-translations

Do you think it's possible to add it? Will you accept a PR?

**Comment by nbourguig** [comment]
Hi,

Yeah the package was build before the introduction of the json based translations files.
It will need some refactoring, but I think it is faisable as there is two main classes responsible of dealing with the files (Reader, Writer).

PR are welcome.

**Comment by happyDemon** [comment]
pull request #45 could be a good starting point
