### ISSUE TITLE
[feature] support to sync diff between local and remote

### ISSUE THREAD

**Issue by ctf0** [nikaia/translation-sheet#36]
is it possible for the package instead of replacing the current lang files with the ones from the google sheet, to check first for the new items in the current and add them to the array from google b4 replacing.

this way you dont lose the extra work made on the local side when u pull the translation from the sheet.

**Comment by nbourguig** [comment]
I can't figure a way off the top of my head to do this. This means some kind of a diff system that could run into conflicts which cannot be solved automatically or maybe present the users a choice to override or not when they run the pull command. 

Pull request are more than welcome.

**Comment by ctf0** [comment]
for now i think the flow could be like 
- sort the array keys
- find the diff using `phpspec/php-diff`
- show a report to the user to decide which copy to use "app or g-sheet version ?"
