### ISSUE TITLE
I need a sample excel docs

### ISSUE THREAD

**Issue by raisrahman** [nikaia/translation-sheet#7]
Hi @nbourguig, I appreciate to your package, it's seems so useful. But, can you give me a sample excel docs? Thanks

**Comment by nbourguig** [comment]
Thx @raisrahman.

In the whole process I am not really using excel. 
All you need is a **blank** google spreadsheet.  (https://docs.google.com/spreadsheets/)

Then when you issue the `prepare` and `push` commands, the sheet will get populated with your translations files.

**Comment by raisrahman** [comment]
yape, thanks a lot @nbourguig 👍 , I'll try
