### ISSUE TITLE
Permission Denied Setting Sheet API

### ISSUE THREAD

**Issue by ardanirohman** [nikaia/translation-sheet#8]
hi @nbourguig  i just try this package when i try 
php artisan translation_sheet:setup
`[Google_Service_Exception]                                 
  {                                                          
    "error": {                                               
      "code": 403,                                           
      "message": "The caller does not have permission",      
      "errors": [                                            
        {                                                    
          "message": "The caller does not have permission",  
          "domain": "global",                                
          "reason": "forbidden"                              
        }                                                    
      ],                                                     
      "status": "PERMISSION_DENIED"                          
    }                                                        
  }`

any solve for this problem?
thanks

**Comment by nbourguig** [comment]
Hi,

I think you need to share the spreadsheet with service account email you created by giving it _CAN EDIT_ permission.

https://github.com/nikaia/translation-sheet#spreadsheet

![image](https://cloud.githubusercontent.com/assets/276832/19359547/f9ee2b20-917a-11e6-996a-59f881c07110.png)

**Comment by ardanirohman** [comment]
wow , thanks it work now. this is cool package for laravel.
